[package]
name = "datalove-credit"
version = "0.0.1"
description = "reference implementation of the datalove credit protocol"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
edition = "2018"

[dependencies]
