[package]
name = "datalove"
version = "0.0.1"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
edition = "2018"

[lib]
name = "datalove"
path = "src/lib.rs"

[[bin]]
name = "datalove"
path = "src/main.rs"
# TODO:
# 	- halt wicker binary progress
#			- start importing wicker lib types to flesh out datalove binary
#			- use comparative impls to make configurable types generic
#			- keep wicker lib and minimal wicker binary for testing and later OSS
#		- impl yaml spec for datalove

[dependencies]
async-std = "1.4"
datalove-base = { path = "crates/base" }
env_logger = "^0.7"
failure = { version = "0.1", features = ["derive"] }
futures = "0.3"
lazy_static = "1"
log = { version = "0.4.8", default-features = false }
lucet-runtime = { version = "^0.5", git = "https://github.com/sunny-g/lucet", branch = "patch-1" }
structopt = "0.2"
wasi-common = "^0.8"
wicker = { path = "crates/wicker" }

[workspace]
members = [
	"crates/base",
	"crates/wicker",
	"examples/sampleipld"
]

[patch.crates-io]
libipld-schema = { path = "../datalove-vendor/rust-ipld/schema" }
lucet-module = { path = "../datalove-vendor/lucet/lucet-module" }
lucet-runtime = { path = "../datalove-vendor/lucet/lucet-runtime" }
lucet-runtime-internals = { path = "../datalove-vendor/lucet/lucet-runtime/lucet-runtime-internals" }
lucet-wasi = { path = "../datalove-vendor/lucet/lucet-wasi" }
rand = { git = "https://github.com/sunny-g/rand", branch = "patch-1" }
