[workspace]
members = [
  "wasiplay",
  "wasiplay/examples/ipld"
  # "lib/core"
]

[patch.crates-io]
libipld-schema = { path = "../datalove-vendor/rust-ipld/schema" }
lucet-module = { path = "../datalove-vendor/lucet/lucet-module" }
lucet-runtime = { path = "../datalove-vendor/lucet/lucet-runtime" }
lucet-runtime-internals = { path = "../datalove-vendor/lucet/lucet-runtime/lucet-runtime-internals" }
lucet-wasi = { path = "../datalove-vendor/lucet/lucet-wasi" }
rand = { git = "https://github.com/sunny-g/rand", branch = "patch-1" }
