[package]
name = "ipld_dag"
version = "0.0.1"
authors = ["Sunny G <sunny.gonna@gmail.com>"]
edition = "2018"

[dependencies]
cid = "0.3.0"
indexmap = "1.0.2"
multibase = "0.6.0"
serde = {version = "1.0.92", features = ["derive"]}
serde-aux = "0.6.1"
serde-value = "0.6.0"
