[package]
name = "datalove-home"
version = "0.0.1"
authors = ["sunny-g <sunny.gonna@gmail.com>"]
edition = "2018"

[dependencies]
datalove-core = { path = "../../crates/core" }
iced = { version = "0.1.1", features = ["async-std"] }
web-view = "0.6.3"
