[package]
name = "ipld_dag_json"
version = "0.0.1"
authors = ["Sunny G <sunny.gonna@gmail.com>"]
edition = "2018"

[dependencies]
ipld_dag = {path = "../ipld_dag"}
serde = "1.0"
serde_json = "1.0"
delegate = "0.2.0"
